---
title: "Gov 50 Final Project"
author: Thoa Hoang
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---

## Project thoughts


The agriculture industry contributes an estimated USD $717 billion to the GDP of Indonesia, Thailand, Philippines, and Vietnam. It employs over 127 million people and accounts for around 30 percent of the entire region’s economy. Yet, the sector has lower productivity and incomes, which contribute to four out of five in rural areas living below the international poverty line. In Southeast Asia, agriculture is closely tied to poverty reduction and economic growth strategy for the region. Farmers in Vietnam depend on fertilizer to increase their crop yield as a way to also increase their income. However, it is unclear how effective fertilizer is on crop yield and if this is consistent across different perennial and annual crops in Vietnam. Through this project, I will use a data set from the Rural and Agricultural 2020 Census.

I hypothesize that fertilizer will increase annual crop yield, however, this may not be consistent across the different types of crops. Additionally, fertilizer usage may also be dependent on cost and how much the Vietnamese government is able to subsidize. Therefore, I hypothesize that the yield may not be consistent, and this may also depend on the actual farm size. I hope to supplement my data with some qualitative information about how much the Vietnamese government subsidized fertilizer in 2020 to see if this may have impacted fertilizer usage. I only have a data set for 2020, but hope to gather another dataset from a different year to do a comparison between fertilizer usage across various years. 

The data set I have separates crops into annuals and perennials. Within each type of crop, there are 5 subsets of crops that are commonly grown by farmers in Vietnam. Data for each crop type has the quantity of fertilizer usage by the area. Additionally, the data set includes information about each farmer, their province, sex, and leave of education. The explanatory variable could be the area of farmland and the fertilizer usage. The outcome variable of interest is the total crop yield. 

Patterns I hope to observe in this data is any relationship between the types of crops that farmers use more fertilizer on. It would be interesting to see whether farmers are using fertilizers more on annual or perennial crops and especially, whether are there crops in that fertilizer usage is heavily concentrated. It would also be interesting to see if the age of the farmer impacts how much fertilizer they use. My dataset has 20,930 observations. The year of birth of the farmers in the dataset range from 1950 to 2000. There are a lot of missing variables so that is something I would need to consider with this data set. 

Milestone 4: Add results from one analysis

Graph 1: Fertilizer Usage on Annual Crops

I observe a positive relationship between the quantity of fertilizer used and the area of land. Logically, this makes sense because as farmable area increases, the quantity of fertilizer used on the land increases. 

Graph 2: Fertilizer Usage on Perennial Crops

I observe a similar positive relationship. Where there seems to be a difference between the annual and perennial crops is the number of observations. Within this dataset, it seems like there are more observations for perennial crops than annual. This could mean that there area more perennial crops being grown in this national survey of Vietnamese farmers. 


```{r}
library("tidyverse")
library("ggplot2")

data.tt2020 <- 
  read_csv("~/R/Tong dieu tra Nong Lam Thuy San 2020/Thoa Notes/Data_TrangTrai_2020.csv")

## Relationship between quantity of fertilizer use on annual crops

theme_set(theme_bw())

ggplot(data = data.tt2020,
       mapping = aes(x = PHANHH01_DT,
                     y = log(PHANHH01_KL)))+
  geom_point()+
  geom_smooth(method = "lm", se = FALSE)+
  scale_x_log10() +
  labs(x = "Area of Fertilizer (m2)" ,
       y = "Quantity of Fertilzer (kg)",
       title = "Fertilzer Usage on Annual Crops")

## Relationship between quantity of fertilzer use on perennial crops

ggplot(data = data.tt2020,
       mapping = aes(x = PHANHH04_DT,
                     y = log(PHANHH04_KL)))+
  geom_point()+
  geom_smooth(method = "lm", se = FALSE)+
  scale_x_log10() +
  labs(x = "Area of Fertilizer (m2)" ,
       y = "Quantity of Fertilzer (kg)",
       title = "Fertilzer Usage on Perennials Crops")
```


